settings:
  discord:
    token: ""
    activity:
      message: "Discord bot"
      type: "LISTENING" # LISTENING, PLAYING, STREAMING, WATCHING, STREAMING

messages:
  no_permissions: "You have no permissions"
  command_logger: "Executed custom command: {command} | By user: {user}" # Variables: {command}, {user}

custom_commands:
  list:
    stop:
      description: "this is a stop command"
      response: "this is a test"
      arguments: {} # Empty arguments
      actions:
        - "stop"
      allowed:
        users: []
        roles:
          - 1148850164610633741
    velocity:
      description: "velocity example"
      response: "command executed"
      arguments:
        1:
          type: "STRING"
          name: "type"
          description: "Gamemode type"
          required: true
          choices:
            1:
              name: "Reload"
              value: "reload"
            2:
              name: "Dump"
              value: "dump"
            3:
              name: "Heap"
              value: "heap"
      actions:
        - "velocity {type}"
      allowed:
        users: []
        roles:
          - 1148850164610633741