settings:
  discord:
    token: ""
    activity:
      message: "Discord bot"
      type: "LISTENING" # LISTENING, PLAYING, STREAMING, WATCHING, STREAMING

messages:
  no_permissions: "You have no permissions"
  command_logger: "Executed custom command: {command} | By user: {user}" # Variables: {command}, {user}

custom_commands:
  list:
    end:
      description: "this is a end command"
      response: "this is a test"
      arguments: {} # Empty arguments
      actions:
        - "end"
      allowed:
        users: []
        roles:
          - 1148850164610633741
    send:
      description: "send command example"
      response: "Send a player to a server"
      arguments:
        1:
          type: "STRING"
          name: "server"
          description: "Servers list"
          required: true
          choices:
            1:
              name: "Survival"
              value: "survival"
            2:
              name: "Prison OP"
              value: "prisonop"
        2:
          type: "STRING"
          name: "player"
          description: "Target player"
          required: true
          choices: {}
      actions:
        - "send {server} {player}"
      allowed:
        users: []
        roles:
          - 1148850164610633741